// remote-vue/src/App.vue
<template>
  <div class="vue-container" style="padding: 20px; border: 2px solid green; margin: 10px">
    <h1>Vue Remote Application</h1>
    <p>This is a Vue remote app component</p>
    <button @click="handleClick">Click Vue Remote Button</button>
  </div>
</template>

<script>
export default {
  name: "App",
  methods: {
    handleClick() {
      alert("Hello from Vue Remote!");
    }
  }
};
</script>

<style scoped>
.vue-container {
  font-family: Arial, sans-serif;
}
</style>

// remote-app/src/App.tsx
import React from "react";

function App() {
  return (
    <div style={{ padding: "20px", border: "2px solid blue", margin: "10px" }}>
      <h1>Remote Application</h1>
      <p>This is a remote app component</p>
      <button onClick={() => alert("Hello from Remote!")}>
        Click Remote Button
      </button>
    </div>
  );
}

export default App;
